<a href="https://colab.research.google.com/github/Dipec001/kreavistromtask1/blob/main/project_euler_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum_below_1000 = 0
num = 0
while num < 1000:
    num += 1
    if num % 5 == 0 or num % 3 == 0:
        sum_below_1000 += num

print(sum_below_1000)

234168

2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
num_list = [1, 2]
iter_1 = 0
iter_2 = 1
x = 0

while True:
    x = num_list[iter_1] + num_list[iter_2]
    if x > 4000000:
        break
    iter_1 += 1
    iter_2 += 1
    num_list.append(x)

print(num_list)

sum_of_even_values = 0
for num in num_list:
    if num % 2 == 0:
        sum_of_even_values += num

print(sum_of_even_values)

[1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578]
4613732

3. The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
def prime_factors(n):
    factors = []
    divisor = 2
    while divisor <= n:
        if n % divisor == 0:
            factors.append(divisor)
            n = n // divisor
        else:
            divisor += 1
    return factors

number_to_factor = 600851475143
factors = prime_factors(number_to_factor)

print("Prime factors of", number_to_factor, "are:", factors)
print("The largest prime factor is:", max(factors))

Prime factors of 600851475143 are: [71, 839, 1471, 6857]
The largest prime factor is: 6857

4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [17]:
def num_is_palindrome(user_input):
    user_input = str(user_input)
    user_input_reverse = user_input[::-1]

    if user_input == user_input_reverse:
        return True
    else:
        return False


palindromic_list = []
for x in range(100, 1000):
    for y in range(100, 1000):
        mul = x * y
        if num_is_palindrome(mul):
            palindromic_list.append(mul)


largest_palindromic_num = 0
for number in palindromic_list:
    if number > largest_palindromic_num:
        largest_palindromic_num = number

print(f"largest palindromic number made from the product of two three-digits is {largest_palindromic_num}")

largest palindromic number made from the product of two three-digits is 906609

5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [ ]:
n = 1
cal = True
while cal:
    n += 1
    if n % 1 == 0 and n % 2 == 0 and n % 3 == 0 and n % 4 == 0 and n % 5 == 0 and n % 6 == 0 \
            and n % 7 == 0 and n % 8 == 0 and n % 9 == 0 and n % 10 == 0 and n % 11 == 0 and n % 12 == 0 \
            and n % 13 == 0 and n % 14 == 0 and n % 15 == 0 and n % 16 == 0 and n % 17 == 0 and n % 18 == 0 and\
            n % 19 == 0 and n % 20 == 0:
        print(n)
        cal = False

232792560

6. The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is, 3025 - 385 = 2640

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [ ]:
first_20 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

first_20_square = []
for num in first_20:
    square = num * num
    first_20_square.append(square)

square_of_sum = sum(first_20) ** 2
sum_of_square = sum(first_20_square)
difference = square_of_sum - sum_of_square

print(square_of_sum)
print(sum_of_square)
print(difference)

44100
2870
41230

7. By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10001st prime number?

In [ ]:
def is_prime(num):
    """function to check if a number is a prime number"""
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True


prime_number_list = []
n = 0
while len(prime_number_list) != 10001:
    n += 1
    if is_prime(n):
        prime_number_list.append(n)


print(max(prime_number_list))

104743

8. A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a^2 + b^2 = c^2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [ ]:
for a in range(1000):
    for b in range(1000):
        c = 1000 - a - b
        if a < b < c and a ** 2 + b ** 2 == c ** 2:
            print(f"a:{a},b:{b},c:{c}")
            print(f"product of abc is {a * b * c}")
            break

a:200,b:375,c:425
product of abc is 31875000

9. The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [ ]:
def is_prime(num):
    """function to check if a number is a prime number"""
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True


prime_numbers_below_2million = []
for num in range(2000000):
    if is_prime(num):
        prime_numbers_below_2million.append(num)

print(sum(prime_numbers_below_2million))

142913828922

10. The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [ ]:
def count_divisors(num):
    count = 0
    sqrt_num = int(num ** 0.5)
    for i in range(1, sqrt_num + 1):
        if num % i == 0:
            count += 2
    if sqrt_num * sqrt_num == num:
        count -= 1
    return count


def find_triangle_number_with_divisors():
    n = 1
    triangle_number = 1

    while True:
        n += 1
        triangle_number += n

        divisors = count_divisors(triangle_number)

        if divisors > 500:
            return triangle_number


result = find_triangle_number_with_divisors()
print(f"The first triangle number with over 500 divisors is {result}")

The first triangle number with over 500 divisors is 76576500